### ISSUE TITLE
Results relative to assetfinder / subfinder

### ISSUE THREAD

**Issue by obheda12** [junnlikestea/vita#24]
Hey cool tool! I was curious to what the benefits of this tool are over other similar tools i.e. subfinder, assetfinder, findomain, etc.

**Comment by junnlikestea** [comment]
I'm not sure if there are any clear advantages over the other tools you've listed, apart from vita adding [SonarSearch](https://github.com/Cgboal/SonarSearch) as a source, and possibly some of the filtering I perform on the results before returning them. 

Some possible disadvantages of vita over some of those existing tools like [Amass](https://github.com/OWASP/Amass) and subfinder would be the lack of recursive enumeration. Vita will only return subdomains of the root domains you gave as input.
